=== murielsouza/python_refutacao/formulapro.dtd
<!ELEMENT ARGUMENTO (PREMISSA*, CONCLUSAO)>
<!ELEMENT PREMISSA (LPRED|CONDICIONAL | DISJUNCAO | CONJUNCAO | BICONDICIONAL)>
<!ELEMENT CONCLUSAO (LPRED|CONDICIONAL | DISJUNCAO | CONJUNCAO | BICONDICIONAL)>
<!ELEMENT LPRED (PREDICATIVO)>
<!ELEMENT CONDICIONAL (ANTECEDENTE, CONSEQUENTE)>
<!ELEMENT DISJUNCAO (PRIM, SEG)>
<!ELEMENT CONJUNCAO (PRIM, SEG)>
<!ELEMENT BICONDICIONAL (PRIM, SEG)>
<!ELEMENT PREDICATIVO (#PCDATA)>
<!ELEMENT ANTECEDENTE (LPRED | CONDICIONAL | DISJUNCAO | CONJUNCAO | BICONDICIONAL)>
<!ELEMENT CONSEQUENTE (LPRED | CONDICIONAL | DISJUNCAO | CONJUNCAO | BICONDICIONAL)>
<!ELEMENT PRIM (LPRED | CONDICIONAL | DISJUNCAO | CONJUNCAO | BICONDICIONAL)>
<!ELEMENT SEG (LPRED | CONDICIONAL | DISJUNCAO | CONJUNCAO | BICONDICIONAL)>
<!ATTLIST LPRED
NEGACAO CDATA #IMPLIED>
<!ATTLIST CONDICIONAL
NEGACAO CDATA #IMPLIED
<!ATTLIST DISJUNCAO
NEGACAO CDATA #IMPLIED
<!ATTLIST CONJUNCAO
NEGACAO CDATA #IMPLIED
<!ATTLIST BICONDICIONAL
NEGACAO CDATA #IMPLIED

=== murielsouza/python_refutacao/formula - Copia.xml
<?xml version="1.0" encoding="UTF-8"?><!-- Q -> P, Q |- P -->
<!DOCTYPE ARGUMENTO SYSTEM "formulapro.dtd">
<ARGUMENTO>
    <PREMISSA>
        <CONDICIONAL CONECTIVO="â†’">
            <ANTECEDENTE>
                <LPRED>
                    <PREDICATIVO>Q</PREDICATIVO>
                </LPRED>
            </ANTECEDENTE>
            <CONSEQUENTE>
                <LPRED>
                    <PREDICATIVO>P</PREDICATIVO>
                </LPRED>
            </CONSEQUENTE>
        </CONDICIONAL>
    </PREMISSA>
    <PREMISSA>
        <LPRED>
            <PREDICATIVO>Q</PREDICATIVO>
        </LPRED>
    </PREMISSA>
    <CONCLUSAO>
        <LPRED>
            <PREDICATIVO>P</PREDICATIVO>
        </LPRED>
    </CONCLUSAO>
</ARGUMENTO>
